### ISSUE TITLE
Escopo e task's.

### ISSUE THREAD

**Issue by C4stro** [C4stro/blog_automatico#1]
- [ ] Especificar tarefas e escopo.

---
- [ ] **Orquestrador (Gerenciador da bagaça toda)** 
   - [ ] Perguntar pelo termo de busca
   - [ ] Perguntar pelo prefixo
   - [ ] Iniciar robô de texto
   - [ ] Iniciar robô de imagens
   - [ ] Iniciar robô de vídeo
   - [ ] Iniciar robô do Youtube

---

- [ ] **Robô de texto(Responsável por toda parte de texto)** 
   - [ ] Estrutura de dados
   - [ ] Pegar conteúdo do Wikipedia
   - [ ] Limpar o conteúdo
   - [ ] Quebrar em sentenças
   - [ ] Pegar a interpretação do Watson
   - [ ] Adicionar tags
   - [ ] Salvar estrutura de dados

---

- [ ] **Robô de imagens(Responsável por toda parte de imagens)** 
   - [ ] Carregar a estrutura de dados
   - [ ] Buscar as imagens do Google imagens
   - [ ] Baixar as imagens
   - [ ] Salvar a estrutura de dados

---

- [ ] **Robô de vídeo(Responsável por toda parte de vídeo)** 
   - [ ] Preparar/redimensionar as imagens
   - [ ] Criar as sentenças com imagens
   - [ ] Criar a thumbnail para o vídeo
   - [ ] Renderizar o vídeo com After Effects 

---

- [ ] **Robô do Youtube(Responsável por todo upload e login no YT)** 
   - [ ] Autenticar com o OAuth
   - [ ] Upload do vídeo
   - [ ] Upload do thumbnail

---

- [ ] **Robô do BD(Responsável por gravar as informações do robo de texto e imagens em BD)** 
   - [ ] Autenticar com o banco de dados
   - [ ] Inserir informações no banco de dados

---

- [ ] **Robô da Notificação(Enviar notificação que BD sofreu inserção de informações por SMS)** 
   - [ ] Encaminhar SMS para celular informando que houve alteração no BD.

**Comment by C4stro** [comment]
**Task 001.** - Concluída com sucesso!

**Comment by C4stro** [comment]
**Task 002.** - Pegar termo de busca - Concluída com sucesso!

**Comment by C4stro** [comment]
Task 002. - Pegar termo de busca ou Google trendings topics - Atualizada com sucesso!

**Comment by C4stro** [comment]
**Task 003.** - Estrutura de dados - Concluída com sucesso!

**Comment by C4stro** [comment]
**Task 003.** - Pegar conteúdo do Wikipedia - Concluída com sucesso!
